### ISSUE TITLE
Gifs are speed up

### ISSUE THREAD

**Issue by aki2273** [ozboar/zoom-sync#3]
Gifs after recoding are speed up too fast. When uploading from the website it doesnt happen.

**Comment by ozwaldorf** [comment]
Can you provide example files to replicate the issue? All the gifs I've tried play at the original speeds

**Comment by aki2273** [comment]
Fixed it but when I install via this command:
cargo install zoom-sync
- it downloads the zoom-sync version 0.1.1
- this has the speed up error.
cargo install --path . downloads
- downloads zoom-sync version 0.1.2

 cargo install zoom-sync
    Updating crates.io index
     Ignored package `zoom-sync v0.1.1` is already installed, use --force to override

 cargo install --path .
  Installing zoom-sync v0.1.2 (C:\Users\XXX\Desktop\Neuer Ordner (3)\zoom-sync)
    Updating crates.io index
     Locking 320 packages to latest compatible versions
      Adding sysinfo v0.32.1 (available: v0.33.0)
    Finished `release` profile [optimized] target(s) in 2.66s

**Comment by ozwaldorf** [comment]
Ahhh, I forgot to make a release on crates.io, will fix soon

**Comment by ozwaldorf** [comment]
released 0.1.2
